FROM node:18-alpine

# Set working directory to /app 
WORKDIR /app

# # Copy package.json to /app
# COPY package*.json .

# # copy dependencies . . means all files in current directory with node_modules and other files
# COPY . .


# # run npm install to install dependencies
# RUN npm install

# # expose port 3000
# EXPOSE 3000


# # npm run start to run the app
# CMD [ "npm","run","start" ]

# Install dependencies again for development
COPY package.json package-lock.json ./
RUN npm install --frozen-lockfile

# Copy the full source code
COPY . ./

# Expose port for the development server
EXPOSE 3001
CMD ["npm", "start"]