export const projects = [
  {
    title: 'CrossJobs',
    description: "CrossJobs.cm is a specialized employment and recruitment platform in Cameroon and around the world. It scours the web to provide unique, free and unlimited access to thousands of job postings from various company websites and job boards around the world.",
    image: '/images/crossjobs.jpg',
    tags: 'Python/Django, PostgreSQL, Bootstrap, Javascript, RabbitMQ, Celery',
    source: 'https://github.com/jafojial/crossjobs',
    visit: 'https://crossjobs.cm',
    id: 0,
  },
  {
    title: 'Cameasygo',
    description: "CAMEASYGO is the first carpooling network in Cameroon. It connects passengers and drivers ready to share their journey by car to allow them to travel everywhere, and without change. It enables thousands of people to travel inexpensively, comfortably and with confidence, sharing the cost of the journey.",
    image: '/images/cameasygo.jpg',
    tags: 'PHP/Symfony 5, PostgreSQL, Twig, Docker, Mercure, Javascript',
    source: 'https://github.com/jafojial/CarPrest2.0',
    visit: 'https://cameasygo.com',
    id: 1,
  },
  {
    title: 'Medicalis',
    description: "Medicalis is a medical management system that helps to manage the information related to health care, appointment, employees and finance. It use related data to produce statictics and help to take the strategic decisions.",
    image: '/images/medicalis.jpg',
    tags: 'JAVA/Spring Boot, Bootstrap, Thymeleaf, PostgreSQL, RabbitMQ',
    source: 'https://github.com/jafojial//medicalis',
    visit: 'https://mis.intelso.cm',
    id: 2,
  },
  {
    title: 'SendIt',
    description: "SendIt is a professional low cost Bulk SMS sending service designed for your company. SendIt provide the best strategy to grow up your business througth instantaneous, reliable and low cost Bulk SMS sending service.",
    image: '/images/sendit.jpg',
    tags: 'JAVA/Spring Boot, Bootstrap, Thymeleaf, PostgreSQL, RabbitMQ',
    source: 'https://github.com/jafojial/sendit',
    visit: 'https://sendit.intelso.cm',
    id: 3,
  },
  {
    title: 'ImmoPlus',
    description: "ImmoPlus is the best online property rental management software. ImmoPlus allows the creation of goods, tenants and rentals and automates the creation of receipts and rental contracts. With ImmoPlus, managing your rental properties has never been easier!",
    image: '/images/immoplus.jpg',
    tags: 'JAVA/Spring Boot, Bootstrap, Thymeleaf, PostgreSQL, RabbitMQ',
    source: 'https://github.com/jafojial/immo-plus',
    visit: 'https://ip.intelso.cm',
    id: 4,
  },
  {
    title: 'ShortU',
    description: "CrossJobs.cm is a specialized employment and recruitment platform in Cameroon and around the world. It scours the web to provide unique, free and unlimited access to thousands of job postings from various company websites and job boards around the world.",
    image: '/images/shortu.jpg',
    tags: 'Python/Django, PostgreSQL, Bootstrap, Javascript, RabbitMQ, Celery',
    source: 'https://github.com/jafojial/shortu',
    visit: 'https://s.intelso.cm',
    id: 5,
  },
  {
    title: 'Cameasygo Mobile',
    description: "An Androïd mobile to access to CAMEASYGO services, the first carpooling network in Cameroon.",
    image: '/images/cameasygo.jpg',
    tags: 'JAVA/Androïd, XML, Retrofit, SQLite',
    source: 'https://github.com/jafojial/carprest-mobile',
    visit: 'https://play.google.com/store/apps/details?id=cm.intelso.dev.carprest',
    id: 6,
  },
  /* {
    title: 'MAC MTN',
    description: "CrossJobs.cm is a specialized employment and recruitment platform in Cameroon and around the world. It scours the web to provide unique, free and unlimited access to thousands of job postings from various company websites and job boards around the world.",
    image: '/images/shortu.jpg',
    tags: 'JAVA/J2EE, PostgreSQL, JSP, KeyStore, Mutual Authentication, SOAP/REST API',
    source: '#',
    visit: '#',
    id: 7,
  },
  {
    title: 'DIGITAL FIRST',
    description: "An Androïd mobile to access to CAMEASYGO services, the first carpooling network in Cameroon.",
    image: '/images/cameasygo.jpg',
    tags: 'JAVA/J2EE, PostgreSQL, RESP API, SQLite',
    source: '#',
    visit: '#',
    id: 8,
  },
  {
    title: 'T24 Integration',
    description: "A Temenos T24 banking system implementation project in which I was in charge of API and routines development, the implementation of interfaces for the integration of billing data, Inquiry and Version",
    image: '/images/cameasygo.jpg',
    tags: 'JAVA, jBASE, XML, CLI, REST API, BATCH',
    source: '#',
    visit: '#',
    id: 9,
  }, */
];

export const TimeLineData = [
  { year: 2015, text: 'Started teaching at NASPT, worked as Project Manager at CDS Technologies', },
  { year: 2016, text: 'Worked as Technical Support Engineer at ADSNET', },
  { year: 2018, text: 'Worked as Developer Engineer at Afriland First Bank Cameroon', },
  { year: 2020, text: 'Launched CrossJobs.cm, a free job aggregator portail', },
  { year: 2021, text: 'Worked as Freelance on multiple projects such as Cameasygo, SendIt, ImmoPlus', },
  { year: 2022, text: 'Created Intelso Sarl, a startup that develops innovative solutions to improve your daily life', },
];